flags: {}
packages:
- '.'
- location:
    git: https://github.com/dimitri-xyz/razao-base
    commit: 5fc12c80aab9757f3aa1202d1abd4a7e172922df
  extra-dep: true

resolver: lts-12.21
extra-deps:
- reactive-banana-1.2.0.0
