flags: {}
packages:
- '.'
- 'dep/bitcoin-type'
- location:
    git: https://github.com/dimitri-xyz/razao-base
    commit: 13d2d7508d48aff30a598c020945de5312124622
  extra-dep: true

extra-deps: []
resolver: lts-8.3
